In [318]:
# ciphertext
ciphertext = """qmnjvsa nv wewc flct vprj tj tvvplvl fv xja vqildhc
xmlnvc nacyclpa fc gyt vfvw. fv wgqyp, pqq pqcs y wsq
rx qmnjvafy cgv tlvhf cw tyl aeuq fv xja tkbv cqnsqs.
lhf avawnc cv eas fuqb qvq tc yllrqr xxwa cfy. psdc uqf
avrqc gefq pyat trac xwv taa wwd dv eas flcbq. vd trawm
vupq quw x decgqcwt, yq yafl vlqs yqklhq! snafq vml
lhvqpawr nqg_vfusr_ec_wawy qp fn wgawdgf."""

In [319]:
#count the number of alphabets in ciphertext
count=0
for i in ciphertext:       
    if(i.isalpha()):
        count+=1 
print(count)

284


In [320]:
#cipher is ciphertext with only alphabets
cipher=""
for i in ciphertext:       # i holds each character in String s for every iteration of loop
    if(i.isalpha()):
        cipher=cipher+i
print(cipher)

qmnjvsanvwewcflctvprjtjtvvplvlfvxjavqildhcxmlnvcnacyclpafcgytvfvwfvwgqyppqqpqcsywsqrxqmnjvafycgvtlvhfcwtylaeuqfvxjatkbvcqnsqslhfavawnccveasfuqbqvqtcyllrqrxxwacfypsdcuqfavrqcgefqpyattracxwvtaawwddveasflcbqvdtrawmvupqquwxdecgqcwtyqyaflvlqsyqklhqsnafqvmllhvqpawrnqgvfusrecwawyqpfnwgawdgf


In [321]:
#print frequency of each letter
import operator

temp={}
for char in ciphertext:
    if char.isalpha():
        temp[char.lower()]=temp.get(char.lower(),0)+1
res=dict(sorted(temp.items(), key=operator.itemgetter(1),reverse=True))
for key,value in res.items():
    print("{} -> {:.1f}%".format(key, value/len(ciphertext)*100))

q -> 8.2%
v -> 7.9%
a -> 6.3%
c -> 6.0%
w -> 5.2%
f -> 5.2%
l -> 4.7%
t -> 3.6%
y -> 3.6%
s -> 3.0%
p -> 3.0%
n -> 2.7%
r -> 2.5%
x -> 2.2%
g -> 2.2%
e -> 1.9%
d -> 1.9%
j -> 1.6%
u -> 1.6%
m -> 1.4%
h -> 1.4%
b -> 0.8%
k -> 0.5%
i -> 0.3%


In [322]:
import numpy as np
from itertools import permutations
from collections import Counter

In [323]:
#takes string and block permutation and returns the permuted string
def blockpermute(str, p):
    l=len(p)
    res=""
    i=0
    for ik in range(len(str)):
        temp=str[i:i+l]
        for j in range(l):
            res=res+temp[p[j]]
        i=i+l
        if i>=len(str):
            break
        
    return res

In [344]:
perms=np.array(list(permutations('01234'))).astype(int)
c=cipher[0:280]       #taking only the multiple of 5 for checking
for p in perms:
    res=blockpermute(c,p)
    
    cnt = Counter(res[x:x+2] for x in range(len(c) - 1))
    
    res=dict(sorted(cnt.items(), key=operator.itemgetter(1),reverse=True))

    for key,value in res.items():
        if value>10:
            print("{} {} -> {:.1f}%".format(p[0:5],key, value/len(c)*100))
        break
    cnt.clear()

[1 0 4 2 3] fa -> 4.6%
[2 4 0 1 3] af -> 3.9%
[3 1 0 4 2] fa -> 3.9%
[3 2 4 0 1] af -> 5.4%


In [327]:
permuted_cipher = blockpermute(c,[3, 2, 4, 0, 1])
print(len(permuted_cipher))

280


In [345]:
#sub is permuted cipher along with the spaces and punctuations like original cipher
i=0
sub=""
for s in ciphertext:
    if s.isalpha() and i<280:
        sub=sub+permuted_cipher[i]
        i+=1
    else:
        sub+=s
print(sub)

jnvqmvn ws afcl ewpv rctt jv jtvllvp jx afv lidvqmx
lhcnca nvlcpcyg cy afv fwtv. gw qfvqp, qyp scyp q rqx
ws jnvqmcyg afv lhvtt wy fcu eqla jx afv vbct kqssqn.
afv lhcnca ws afv eqbv uqy cl qtrqxl rcaf xwd. scyp afv
uqgce rqyp afqa rctt tva xwd wda ws afv eqbvl. ca rwdtp
uqmv xwd q uqgcecqy, yw tvll afqy kqssqn! lhvqm afv
hqllrwnp afv_uqgce_ws_rqyp aw gw afnwdgf.


In [346]:
#substitution same as assignment 1
alphabet = 'abcdefghijklmnopqrstuvwxyz'
key = 'tviuchgpqbjskr?dawflmeoyn?'
def decrypt(ciphertext, key, alphabet):
    keyMap = dict(zip(alphabet, key))
    return ''.join(keyMap.get(c, c) for c in ciphertext)

plaintext = decrypt(sub, key, alphabet)

print(plaintext)

breaker of this code will be blessed by the squeaky
spirit residing in the hole. go ahead, and find a way
of breaking the spell on him cast by the evil jaffar.
the spirit of the cave man is always with you. find the
magic wand that will let you out of the caves. it would
make you a magician, no less than jaffar! speak the
password the_magic_of_wand to go through.
